//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Import_and_Export
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMIMEntities : DbContext
    {
        public CMIMEntities()
            : base("name=CMIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<ActivityPlace> ActivityPlace { get; set; }
        public virtual DbSet<Bordereau> Bordereau { get; set; }
        public virtual DbSet<bu> bu { get; set; }
        public virtual DbSet<Conjoint> Conjoint { get; set; }
        public virtual DbSet<Dossiers> Dossiers { get; set; }
        public virtual DbSet<Enfant> Enfant { get; set; }
        public virtual DbSet<list> list { get; set; }
        public virtual DbSet<Regul_Emp> Regul_Emp { get; set; }
        public virtual DbSet<Regularisation> Regularisation { get; set; }
        public virtual DbSet<Remboursser> Remboursser { get; set; }
        public virtual DbSet<sites> sites { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<employees> employees { get; set; }
    }
}
