//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Import_and_Export
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dossiers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dossiers()
        {
            this.list = new HashSet<list>();
        }
    
        public string referance { get; set; }
        public string employeematricule { get; set; }
        public Nullable<long> ConjointId { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime dateDossier { get; set; }
        public Nullable<System.DateTime> dateLunette { get; set; }
        public double montant { get; set; }
        public double Mt_radio { get; set; }
        public double Mt_analyse { get; set; }
        public double MtSoins_D { get; set; }
        public double MtProthese_D { get; set; }
        public double Devis_D { get; set; }
        public double MtVisite_M { get; set; }
        public double MtPharmacie_M { get; set; }
        public double MtVisite_L { get; set; }
        public double MtCadre_L { get; set; }
        public double MtGi_L { get; set; }
        public double avance { get; set; }
        public double rembourse { get; set; }
        public double diff { get; set; }
        public Nullable<long> rembourssementId { get; set; }
        public Nullable<long> BordereauId { get; set; }
        public string etat { get; set; }
        public string Type { get; set; }
        public Nullable<long> EnfantId { get; set; }
        public long UserId { get; set; }
    
        public virtual Bordereau Bordereau { get; set; }
        public virtual Conjoint Conjoint { get; set; }
        public virtual employees employees { get; set; }
        public virtual Enfant Enfant { get; set; }
        public virtual Remboursser Remboursser { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<list> list { get; set; }
    }
}
