//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Import_and_Export
{
    using System;
    using System.Collections.Generic;
    
    public partial class list
    {
        public long listId { get; set; }
        public long RembouserembourssementId { get; set; }
        public string Dossierreferance { get; set; }
        public double montant { get; set; }
    
        public virtual Dossiers Dossiers { get; set; }
        public virtual Remboursser Remboursser { get; set; }
    }
}
