//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Import_and_Export
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regul_Emp
    {
        public long regul_empID { get; set; }
        public Nullable<long> RégularisationRegularisationID { get; set; }
        public string EmployeeMatricule { get; set; }
        public double Total { get; set; }
    
        public virtual Regularisation Regularisation { get; set; }
        public virtual employees employees { get; set; }
    }
}
